### ISSUE TITLE
Request for Dataset

### ISSUE THREAD

**Issue by cddc22** [AsteriosPar/mmWave_MSc#9]
Hi AsteriosPar ,

I hope you are doing well. I have been exploring your repository and am very impressed with your work.

I noticed that the dataset used in your project is not included in the repository. Could you please provide access to the dataset? It would be very helpful for my research and understanding of the project.

Thank you for your assistance!

Best regards.

**Comment by AsteriosPar** [comment]
Hi cddc22,

The dataset is indeed not included yet. I have been working on improving it and balancing the data and hopefully it will be publicly available soon. 

I will add a pre-trained model that should work for cases captured with the same sensor in a range 1m - 7m. 

Best,
Asterios
